data = [
    {"name": "Cristiano Ronaldo", "followers": 550_000_000, "description": "Footballer", "location": "Portugal"},
    {"name": "Kylie Jenner", "followers": 400_000_000, "description": "Entrepreneur & TV Personality", "location": "USA"},
    {"name": "Selena Gomez", "followers": 380_000_000, "description": "Singer & Actress", "location": "USA"},
    {"name": "Dwayne Johnson", "followers": 350_000_000, "description": "Actor & Wrestler", "location": "USA"},
    {"name": "Kim Kardashian", "followers": 350_000_000, "description": "TV Personality & Entrepreneur", "location": "USA"},
    {"name": "Ariana Grande", "followers": 350_000_000, "description": "Singer & Actress", "location": "USA"},
    {"name": "Lionel Messi", "followers": 300_000_000, "description": "Footballer", "location": "Argentina"},
    {"name": "Beyoncé", "followers": 300_000_000, "description": "Singer & Actress", "location": "USA"},
    {"name": "Virat Kohli", "followers": 275_000_000, "description": "Cricketer", "location": "India"},
    {"name": "Justin Bieber", "followers": 260_000_000, "description": "Singer", "location": "Canada"},
    {"name": "Kendall Jenner", "followers": 250_000_000, "description": "Model & TV Personality", "location": "USA"},
    {"name": "Taylor Swift", "followers": 250_000_000, "description": "Singer & Songwriter", "location": "USA"},
    {"name": "Neymar Jr", "followers": 250_000_000, "description": "Footballer", "location": "Brazil"},
    {"name": "Zendaya", "followers": 200_000_000, "description": "Actress & Singer", "location": "USA"},
    {"name": "Cardi B", "followers": 160_000_000, "description": "Rapper & Actress", "location": "USA"},
    {"name": "Miley Cyrus", "followers": 150_000_000, "description": "Singer & Actress", "location": "USA"},
    {"name": "Billie Eilish", "followers": 140_000_000, "description": "Singer & Songwriter", "location": "USA"},
    {"name": "Jennifer Lopez", "followers": 130_000_000, "description": "Singer & Actress", "location": "USA"},
    {"name": "Kourtney Kardashian", "followers": 130_000_000, "description": "TV Personality", "location": "USA"},
    {"name": "Rihanna", "followers": 120_000_000, "description": "Singer & Businesswoman", "location": "Barbados"},
    {"name": "Ellen DeGeneres", "followers": 110_000_000, "description": "TV Host & Comedian", "location": "USA"},
    {"name": "Drake", "followers": 95_000_000, "description": "Rapper & Singer", "location": "Canada"},
    {"name": "David Beckham", "followers": 80_000_000, "description": "Footballer", "location": "UK"},
    {"name": "Gal Gadot", "followers": 75_000_000, "description": "Actress & Model", "location": "Israel"},
    {"name": "Shakira", "followers": 75_000_000, "description": "Singer & Dancer", "location": "Colombia"},
    {"name": "Chris Hemsworth", "followers": 70_000_000, "description": "Actor", "location": "Australia"},
    {"name": "Emma Watson", "followers": 60_000_000, "description": "Actress & Activist", "location": "UK"},
]
